---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: word-count
  name: word-count
  annotations:
    {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: word-count
  name: word-count
data:
  uwsgi-dynamic.yaml: "{}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: word-count
  name: word-count
rules:
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - "configmaps"
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: word-count
  name: word-count
subjects:
  - kind: ServiceAccount
    name: word-count
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: word-count
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: word-count
  name: word-count
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: word-count
  type: "ClusterIP"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: word-count
  name: word-count
spec:
  selector:
    matchLabels:
      app: word-count
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: word-count
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"

    spec:
      serviceAccountName: word-count
      containers:
        - name: word-count
          image: "word-count:0.0.5"
          imagePullPolicy: "IfNotPresent"
          args:
            ["--yaml", "/etc/config/uwsgi-dynamic.yaml"]
          env:
            - name: UWSGI_SOCKET 
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: FILE_FORM_FIELD
              value: data
            - name: PROMETHEUS_PATH
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.annotations['prometheus.io/path']"
          ports:
            - containerPort: 5000
              name: main
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "768m"
              memory: "1024Mi"

          volumeMounts:
            - name: config-volume
              mountPath: /etc/config

      volumes:
        - name: config-volume
          configMap:
            name: word-count
